name: Build, Test and deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Create database
        run: touch ./database/database.mysql

      - name: Copy .env
        run: cp .env.test .env

      - name: Install app
        run: composer install

      - name: Run migrations
        run: php artisan migrate
        continue-on-error: true

      - name: Test PHPStan
        run: ./vendor/bin/phpstan analyse
        continue-on-error: true

      - name: Test PHPUnit
        run: ./vendor/bin/phpunit
        continue-on-error: true
